import { useSession } from 'next-auth/react';
import Head from 'next/head';
import { useSelector } from 'react-redux';
import Login from '../components/login';
import useAuthCheck from '../hooks/useAuthCheck';
export default function Home() {
  const { data: session } = useSession();
  const { loggedInUser } = useSelector((state) => state.user);
  console.log(loggedInUser);
  const authChecked = useAuthCheck();
  return !authChecked ? (
    <div>Checking Authentication...</div>
  ) : (
    <div className="h-screen  bg-gray-100 ">
      {loggedInUser ? (
        <div>
          <Head>
            <title>Quiz App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>

          <main className="bg-white"></main>
        </div>
      ) : (
        <Login />
      )}
    </div>
  );
}
