import Head from 'next/head';
import { useContext, useState } from 'react';
import Login from '../components/login';
import { AuthContext } from '../context/AuthProvider';

export default function Home() {
  const [loggedInUser, setLoggedInUser] = useState(false);
  const { user } = useContext(AuthContext);
  console.log(user);
  return (
    <div className="h-screen  bg-gray-100 ">
      {user?.email ? (
        <div>
          <Head>
            <title>Quiz App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>

          <main className="bg-white"></main>
        </div>
      ) : (
        <Login />
      )}
    </div>
  );
}
